# Site settings
title:          De Rebus
description:    "Ich über die Dinge"
url:            "https://jakobhillebrand.github.io/derebus"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jakob Hillebrand
  url:          https://jakobhillebrand.github.io/derebus/
  email:        jakobhillebrand2001@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

default:
  excerpt_separator: <!--more-->

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale

related_posts_section:
  max_count:        5
  min_common_tags:  1

social:
  email: jakobhillebrand2001@gmail.com
  github: https://github.com/jakobhillebrand/derebus
  reddit: https://www.reddit.com/r/DeRebus/

sponsoring:
  ko-fi: https://ko-fi.com/jakobhillebrand
