# Site settings
title:          De Rerum
description:    "Ich über die Dinge"
url:            "https://jakobhillebrand.github.io/derebus/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Jakob Hillebrand
  url:          https://jakobhillebrand.github.io/derebus/
  email:        jakobhillebrand2001@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jemoji

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
